'''
.. py:module:: sentence
    :platform: Unix
    
Text generation for new age context.

Original vocabulary and sentence templates by Seb Pearce. 
Pythonified and altered by Simo Linkola.
'''
import random
import re

vocabs = {
    'nEnergy': [
       'power',
       'energy',
       'radiation',
       'vibration',
       'entanglement',
       'force',
       'meaning',
       'purpose',
       'knowledge'
    ],   
    'nCosmos': [
      'cosmos',
      'quantum soup',
      'infinite',
      'universe',
      'galaxy',
      'multiverse',
      'grid',
      'quantum matrix',
      'totality',
      'quantum cycle',
      'nexus',
      'planet',
      'solar system',
      'world',
      'stratosphere',
      'dreamscape',
      'biosphere',
      'space',
      'reality'
    ],
    'nPerson': [
      'being',
      'child',
      'traveller',
      'entity',
      'lifeform',
      'wanderer',
      'visitor',
      'prophet',
      'seeker',
      'soul',
      'healer',
      'sage',
      'shaman'
    ],
    'nPersonPlural': [
      'beings',
      'travellers',
      'entities',
      'lifeforms',
      'dreamweavers',
      'adventurers',
      'pilgrims',
      'warriors',
      'messengers',
      'dreamers',
      'storytellers',
      'seekers',
      'healers',
      'sages',
      'shamans'
    ],
    'nMass': [
      'consciousness',
      'nature',
      'beauty',
      'knowledge',
      'truth',
      'life',
      'healing',
      'potential',
      'freedom',
      'purpose',
      'coherence',
      'choice',
      'passion',
      'understanding',
      'balance',
      'growth',
      'inspiration',
      'conscious living',
      'energy',
      'health',
      'spacetime',
      'learning',
      'being',
      'wisdom',
      'stardust',
      'sharing',
      'science',
      'curiosity',
      'hope',
      'wonder',
      'faith',
      'fulfillment',
      'peace',
      'rebirth',
      'self-actualization',
      'presence',
      'power',
      'will',
      'flow',
      'potential',
      'potentiality',
      'chi',
      'intuition',
      'synchronicity',
      'wellbeing',
      'joy',
      'love',
      'karma',
      'life-force',
      'awareness',
      'guidance',
      'transformation',
      'grace',
      'divinity',
      'non-locality',
      'inseparability',
      'interconnectedness',
      'transcendence',
      'empathy',
      'insight',
      'rejuvenation',
      'ecstasy',
      'aspiration',
      'complexity',
      'serenity'
    ],
    'nMassBad': [
      'turbulence',
      'pain',
      'suffering',
      'stagnation',
      'desire',
      'greed',
      'selfishness',
      'ego',
      'dogma',
      'illusion',
      'delusion',
      'yearning',
      'discontinuity',
      'materialism'
    ],
    'nOurPlural': [
      'souls',
      'lives',
      'dreams',
      'hopes',
      'bodies',
      'hearts',
      'brains',
      'third eyes',
      'essences',
      'chakras'
    ],
    'nPath': [
      'circuit',
      'mission',
      'journey',
      'path',
      'quest',
      'vision quest',
      'story',
      'myth'
    ],
    'nOf': [
      'quantum leap',
      'evolution',
      'spark',
      'lightning bolt',
      'reintegration',
      'vector',
      'rebirth',
      'revolution',
      'wellspring',
      'fount',
      'source',
      'fusion',
      'canopy',
      'flow',
      'network',
      'current',
      'transmission',
      'oasis',
      'quantum shift',
      'paradigm shift',
      'metamorphosis',
      'harmonizing',
      'reimagining',
      'rekindling',
      'unifying',
      'ozmosis',
      'vision',
      'uprising',
      'explosion',
      'transmutation'
    ],
    'ing': [
      'flowering',
      'unfolding',
      'blossoming',
      'awakening',
      'deepening',
      'refining',
      'maturing',
      'evolving',
      'summoning',
      'unveiling',
      'redefining',
      'condensing',
      'ennobling',
    ],
    'ingBad': [
       'troubling',
       'unsettling',
       'forbidding',
       'menacing',
       'alarming',
       'weakening',
       'brooding',
       'agonising',
       'threatening',
       'depressing',
       'stalking'
    ],
    'adj': [
      'enlightened',
      'zero-point',
      'quantum',
      'high-frequency',
      'Vedic',
      'non-dual',
      'conscious',
      'sentient',
      'sacred',
      'infinite',
      'primordial',
      'ancient',
      'powerful',
      'spiritual',
      'higher',
      'advanced',
      'internal',
      'sublime',
      'technological',
      'dynamic',
      'life-affirming',
      'sensual',
      'unrestricted',
      'ever-present',
      'endless',
      'ethereal',
      'astral',
      'cosmic',
      'spatial',
      'transformative',
      'unified',
      'non-local',
      'mystical',
      'divine',
      'self-aware',
      'magical',
      'amazing',
      'interstellar',
      'unlimited',
      'authentic',
      'angelic',
      'karmic',
      'psychic',
      'pranic',
      'consciousness-expanding',
      'perennial',
      'heroic',
      'archetypal',
      'mythic',
      'intergalatic',
      'holistic',
      'joyous',
      'sublime', 
      'external',
      'sacred',
      'ayurvedic',
      'ephemeral',
      'outlandish'
    ],
    'adjBig': [
      'epic',
      'unimaginable',
      'colossal',
      'unfathomable',
      'magnificent',
      'enormous',
      'jaw-dropping',
      'ecstatic',
      'powerful',
      'untold',
      'astonishing',
      'incredible',
      'breathtaking',
      'staggering',
      'humongous',
      'hidden',
      'unspoken'
    ],
    'adjBad': [
      'evil',
      'stalking',
    ],
    'adjWith': [
      'aglow with',
      'buzzing with',
      'beaming with',
      'full of',
      'overflowing with',
      'radiating',
      'bursting with',
      'electrified with',
      'gleaming with',
      'energized with',
      'constructed of',
    ],
    'adjPrefix': [
      'ultra-',
      'supra-',
      'hyper-',
      'pseudo-',
      'nano-'
    ],
    'vtMass': [
      'inspire',
      'integrate',
      'ignite',
      'discover',
      'rediscover',
      'foster',
      'release',
      'manifest',
      'harmonize',
      'engender',
      'bring forth',
      'bring about',
      'create',
      'spark',
      'reveal',
      'generate',
      'leverage'
    ],
    'vtPerson': [
      'enlighten',
      'inspire',
      'empower',
      'unify',
      'strengthen',
      'recreate',
      'fulfill',
      'change',
      'develop',
      'heal',
      'awaken',
      'synergize',
      'ground',
      'bless',
      'beckon',
      'transform'
    ],
    'viPerson': [
      'exist',
      'believe',
      'grow',
      'live',
      'dream',
      'reflect',
      'heal',
      'vibrate',
      'self-actualize',
      'seek'
    ],
    'vtDestroy': [
      'destroy',
      'eliminate',
      'shatter',
      'disrupt',
      'sabotage',
      'exterminate',
      'obliterate',
      'eradicate',
      'extinguish',
      'erase',
      'confront',
      'diminish',
      'destabilize'
    ],
    'nTheXOf': [
      'richness',
      'truth',
      'growth',
      'nature',
      'healing',
      'knowledge',
      'meaning',
      'purpose',
      'need'
    ],
    'ppPerson': [
      'awakened',
      're-energized',
      'recreated',
      'reborn',
      'guided',
      'aligned'
    ],
    'ppThingPrep': [
      'enveloped in',
      'transformed into',
      'nurtured by',
      'opened by',
      'immersed in',
      'engulfed in',
      'baptized in'
    ],
    'fixedAdvP': [
      'through non-local interactions',
      'inherent in nature',
      'at the quantum level',
      'at the speed of light',
      'of unfathomable proportions',
      'on a cosmic scale',
      'devoid of self',
      'of the creative act',
    ],
    'fixedAdvPPlace': [
      'in this dimension',
      'outside time',
      'within the Godhead',
      'at home in the cosmos',
    ],
    'fixedNP': [
      'expanding wave functions',
      'superpositions of possibilities',
      'electromagnetic forces',
      'electromagnetic resonance',
      'molecular structures',
      'atomic ionization',
      'electrical impulses',
      'a resonance cascade',
      'bio-electricity',
      'ultrasonic energy',
      'sonar energy',
      'vibrations',
      'frequencies',
      'four-dimensional superstructures',
      'ultra-sentient particles',
      'sub-atomic particles',
      'chaos-driven reactions',
      'supercharged electrons',
      'supercharged waveforms',
      'pulses',
      'transmissions',
      'morphogenetic fields',
      'bio-feedback',
      'meridians',
      'morphic resonance',
      'cellular knowledge',
      'quantum information'
    ],
    'nSubject': [
      'alternative medicine',
      'astrology',
      'tarot',
      'crystal healing',
      'the akashic record',
      'feng shui',
      'acupuncture',
      'homeopathy',
      'aromatherapy',
      'ayurvedic medicine',
      'faith healing',
      'prayer',
      'astral projection',
      'Kabala',
      'reiki',
      'naturopathy',
      'numerology',
      'affirmations',
      'the Law of Attraction'
    ],
    'vOpenUp': [
      'open up',
      'give us access to',
      'enable us to access',
      'remove the barriers to',
      'clear a path toward',
      'let us access',
      'tap into',
      'align us with'
    ],
    'vTraverse': [
      'traverse',
      'walk',
      'follow',
      'engage with',
      'go along',
      'roam',
      'navigate',
      'wander',
      'embark on',
      'lead'
    ],
    'advAlways': [
      'always',
      'wholly',
      'consistently',
      'repeatedly',
      'everlastingly',
      'eternally',
      'endlessly',
      'perpetually',
      'forever'
    ],
    'advPartly': [
       'partly', 
       'incompletely',
       'inadequately',  
    ],
    'timesPlural': [
       'times',
       'days',
       'nights',
       'solar cycles',
       'eons',
       'moments',
       'years',
       'days of judgement'
    ],
    'vBegin': [
       'begin',
       'start',
       'find',
       'actualize',
       'make',
       'initiate',
       'commence',
       'lead',
       'establish'
    ],
    'vFeel': [
       'feel',
       'touch',
       'sense',
       'see',
       'realize',
       'believe',
       'listen'
    ],
    'myFriend': [
        'my friend',
        'my sister',
        'my brother',
        'connected one',
        'awakened one',
        'fellow warrior',
        'kindred spirit',
        'spirit warrior'
    ],
    'vGreeting': [
       'hey',
       'hello',
       'ciao',
       'aloha',
       'my brother',
       'my friend',
       'my sister',
    ],
    'nConfirmation': [
       'yes',
       'surely',
       'sure',
       'of course',
       'definitely',
       'certainly',
    ],
    'nMotor': [
       'driver',
       'primus motor',
       'incentive',
       'driving force',
       'manipulator',
       'animator'
    ],
    'vCallingTo': [
       'reaching to',
       'calling to',
       'stretching to',
       'embracing',
       'encompassing',
       'spreading to',
       'spanning to'         
    ],
    'vThink': [
       'think',
       'feel',
       'sense', 
       'understand',
       'acknowledge',
       'approve',
       'realize',
       'believe'
    ],
    'nReason': [
       'goal',
       'reason',
       'ambition',
       'intent',
       'purpose',
       'objective',
       'destination',
       'desire',
       'target',
    ],
    'nInstitution': [
       'science',
       'church',
       'politics',
       'meditation',
       'society'
    ],
    'nSign': [
       'sign',
       'symbol',
       'omen',
       'premonition',
       'harbinger',
       'auspice',
       'augury'
    ],
    'vCome': [
       'come',
       'manifest',
       'materialize',
       'transpire',
       'occur'
    ],
    'nPersonLife': [
        'day',
        'life',
        'mind',
        'soul',
        'existence',
        'third eye',
        'heart',
        'thruth'
    ],
    'nBattle': [
        'battle',
        'confrontation',
        'conflict',
        'struggle',
        'collision',
        'disharmony'
    ],
    'adjPresent': [
        'prominent',
        'present',
        'evident',
        'current',
        'in process',
        'extant',
    ],
    'nExploration': [
         'exploration',
         'research',
         'analysis',
         'expedition',
         'study',
         'inspection',
         'introspection',
         'examination'
    ],
    'adjCareful': [
         'careful',
         'meticulous',
         'rigorous',
         'vigilant',
         'cautious',
         'mindful',
         'conscious',
         'sensible',
         'enlightened'
    ],
    'vFound': [
         'found',
         'started',
         'begun',
         'created',
         'formed',
         'initiated',
         'realized',
         'planted'
    ]
}

templates = [
    '<> nMass is the <> nMotor of <> nMass',
    '<> nMass is the nTheXOf of <> nMass, and of us',
    'You and I are <> nPersonPlural of the <> nCosmos',
    'We viPerson as <> fixedNP',
    'We viPerson, we viPerson, we are reborn in <> nCosmos',
    'Nothing is impossible for <> nPerson',
    'This <> life is nothing short of a <> ing nOf of adj <> nMass',
    '<> consciousness consists of fixedNP of <> quantum nEnergy',
    'nMass means a <> ing of the <> adj',
    'The <> nReason of fixedNP is to plant the <> seeds of <> nMass rather than <> nMassBad',
    '<> nMass is a <> constant',
    'By <> ing, we viPerson as <> beings',
    'This <> nCosmos is adjWith fixedNP',
    'To vTraverse the <> nPath is to become one with it',
    'We can no longer afford to live with <> nMassBad',
    'Without <> nMass, one cannot viPerson',
    'Only a nPerson of the <> nCosmos may vtMass this <> nOf of <> nMass',
    'vGreeting, <> nPerson, you must take a stand against <> nMassBad',
    'nConfirmation, it is possible to vtDestroy the <> things that can vtDestroy us, but not without <> nMass on our side',
    '<> nMassBad is the <> antithesis of <> nMass',
    'vGreeting, you may be ruled by <> nMassBad without realizing it',
    'Do not let <> vtDestroy the nTheXOf of your <> nPath',
    'the <> complexity of the present <> time seems to demand a ing of our <> nOurPlural if we are going to survive',
    '<> nMassBad is born in the <> gap where <> nMass has been excluded',
    'Where there is <> nMassBad, <> nMass cannot thrive',
    'In these ingBad <> timesPlural the <> nMassBad can vtDestroy all adj <> nMass',
    'Soon there will be a ing of <> nMass the likes of which the <> nCosmos has never seen',
    'It is time to take <> nMass to the next <> level',
    'Imagine a <> ing of what could be',
    '<> Eons from now, we <> nPersonPlural will viPerson like never before as we are ppPerson by the <> nCosmos',
    'This is a <> nSign of <> timesPlural to vCome',
    'The <> future will be a adj <> ing of <> nMass',
    'This <> nPath never ends',
    'We must learn how to lead adj <> lives in the face of <> nMassBad',
    'We must vtPerson our <> selves and vtPerson others',
    'The nOf of <> nMass is now happening worldwide',
    'We are being called to explore the <> nCosmos itself as a <> interface between <> nMass and <> nMass',
    'It is in <> ing that we are ppPerson',
    'This <> nCosmos is approaching a <> tipping point',
    'Although you, myFriend, may not vThink it, you are <> adj',
    '<> nPerson, look within and vtPerson yourself',
    'vGreeting, <> nPerson, have you vFound your <> nPath?',
    'How should you vTraverse this <> adj <> nCosmos?',
    'It can be difficult to know where to vBegin your <> nPath',
    'If you have never experienced this <> nOf fixedAdvP, it can be difficult to viPerson',
    'This <> nCosmos is vCallingTo you via fixedNP. Can you vFeel it?',
    'vGreeting, adj <> nPerson, are you able to vFeel the <> nCosmos? Do you really vFeel it?',
    'vGreeting, myFriend. Do you vThink that our <> nOurPlural are ppThingPrep adj <> nMassBad?',
    'myFriend, how does ing <> one vFeel this, adj <> nMass?',
    'vGreeting, <> nPerson, is your nPersonLife full of adj <> nEnergy?',
    'Throughout <> history, <> humans have been interacting with the <> nCosmos via fixedNP',
    '<> nCosmos has advAlways been adjWith <> nPersonPlural whose <> nOurPlural are ppThingPrep <> nMass',
    'Our adj <> conversations with other <> nPersonPlural have led to a ing of adjPrefix adj <> consciousness',
    'vGreeting, we are in the midst of a adj <> ing of <> nMass that will vOpenUp the <> nCosmos itself',
    'Who are we, <> nPersonPlural? Where on the great <> nPath will we be ppPerson?',
    'vGreeting, we are at a <> crossroads of <> nMass and <> nMassBad',
    'Today, nInstitution tells us that the <> essence of <> nature is <> nMass',
    'This adj <> nMass requires adjCareful <> nExploration',
    'Through <> nSubject, our <> nOurPlural are ppThingPrep nMass',
    'nSubject may be the <> solution to what\'s holding you back from a adjBig nOf of <> nMass',
    'myFriend, you will soon be ppPerson by a <> nEnergy deep within yourself -- a <> nEnergy that is adj, adj',
    'As you viPerson, you will enter into infinite <> nMass that transcends <> understanding',
    'The <> nBattle between adj <> nMass and ingBad <> nMassBad is advAlways adjPresent',
    'The nReason of <> nInstitution is to advAlways vBegin <> nOf of <> nMass',
    'Are you with us, myFriend, the adj <> nPerson?',
    'For every ppPerson <> nPerson there comes a <> time when one needs to viPerson oneself',
    'Do you see this adj <> nMass within your grasp adj nPerson?'
]


def _random_word(pos):
    r = random.randint(0, len(vocabs[pos]) - 1)
    return vocabs[pos][r]


def _fix_format(sentence):
    sentence = sentence.strip()
    # Capitalize
    sentence = sentence[0].upper() + sentence[1:]
    # Add last punctuation if missing.
    if sentence[-1] not in '.!?':
        sentence += '.';
    
    # Strip possible spaces before punctuation
    result = re.sub('( [,.;\?!])', lambda x: x.group(0)[-1], sentence);
    # Try to fix 'a epic' to 'an epic'. Not fool proof as naively only considers
    # if the next word starts with a vowel or not.
    result = re.sub('(^|\W)([Aa]) ([aeiou])', lambda x: x.group(1)+x.group(2)+"n "+x.group(3), result)
    # take care of prefixes (delete the space after the hyphen)
    result = re.sub('([^- ])- ', lambda x: x.group(1)+'-', result);
    return result


def generate_sentence():
    template = random.choice(templates)
    template = re.sub('[.,;?!]', lambda x: " "+x.group(0), template)
    template = template.split(" ")
    result = ""
    
    for s in template:
        if s in vocabs:
            result += _random_word(s)
        else:
            result += s;
        result += ' ';
    
    return _fix_format()


def generate_text(ns):
    text = reduce(lambda x,y: " ".join([x,generate_sentence()]), xrange(ns), "")
    return text.strip()


if __name__ == '__main__':
    print generate_sentence()



